#include <stdio.h>

// Declare the yylex function generated by flex
extern int yylex(void);

// Declare the yytext variable to access matched text
extern char* yytext;

int main(void) {
    int token;

    while ((token = yylex()) != 0) {
        printf("Token: %d, Text: %s\n", token, yytext);
    }

    return 0;
}